# Generated by Django 6.0.7 on 2026-07-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الكتاب')),
                ('author', models.CharField(max_length=100, verbose_name='المؤلف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('genre', models.CharField(max_length=50, verbose_name='التصنيف')),
                ('published_year', models.IntegerField(blank=True, null=True, verbose_name='سنة النشر')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='عدد الصفحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'كتاب',
                'verbose_name_plural': 'الكتب',
                'ordering': ['-created_at'],
            },
        ),
    ]
